{
 "title": "Home Assistant",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Internet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "homeassistant_binary_sensor_state{entity=\"binary_sensor.internet_uptime\"} ",
     "legendFormat": "Availibility"
    }
   ]
  },
  {
   "title": "Barometric Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_unit_mbar{entity=\"sensor.home_pressure\", friendly_name=\"Pressure\"}",
     "legendFormat": "Exterior"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.home_humidity\", friendly_name=\"Humidity\"}",
     "legendFormat": "Exterior"
    },
    {
     "expr": "homeassistant_sensor_humidity_percent",
     "legendFormat": "{{entity}}"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_unit_mph{entity=\"sensor.home_wind_speed\", friendly_name=\"Wind Speed\"}",
     "legendFormat": "mph"
    }
   ]
  },
  {
   "title": "Zigbee Battery",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_battery_percent{domain=\"sensor\"}",
     "legendFormat": "{{entity}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_unit_f{entity=\"sensor.home_temperature\"}",
     "legendFormat": "Exterior"
    },
    {
     "expr": "homeassistant_sensor_temperature_celsius * 9/5 + 32",
     "legendFormat": "{{entity}}"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_unit_mph{entity=\"sensor.home_wind_speed\", friendly_name=\"Wind Speed\"}",
     "legendFormat": "mph"
    }
   ]
  }
 ]
}