apiVersion: 1

datasources:
- name: Thanos
  type: prometheus
  id: 1
  orgId: 1
  uid: C3hREdJnk
  typeName: Prometheus
  access: proxy
  url: http://thanos_query:19192
  basicAuth: false
  isDefault: true
  readOnly: true
