version: "2"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2022.01.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: 'America/New_York'
      DNSMASQ_USER: 'root'
      WEBPASSWORD: 'password'
    volumes:
      - '/data/etc-pihole:/etc/pihole'
      - '/data/etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
  node_exporter:
    image: prom/node-exporter-linux-arm64:v1.3.1
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
  cadvisor:
    # no arm image yet image: gcr.io/cadvisor/cadvisor:v0.39.3
    build:
      context: ./
      dockerfile: Dockerfile.cadvisor
    container_name: cadvisor
    privileged: true
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    ports:
      - 8080:8080
