apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  labels:
    app: pihole
  name: pihole-udp
spec:
  #externalTrafficPolicy: Cluster
  ports:
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: dns-udp
  - name: client-udp
    port: 67
    protocol: UDP
    targetPort: client-udp
  selector:
    app: pihole
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: EXTERNAL_IP_ADDRESS