version: "2"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.7.7
    container_name: jellyfin
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'America/New_York'
    volumes:
      - /data/jellyfin-config:/config
      - /data/media:/data
    ports:
      - 80:8096
    restart: unless-stopped
  node_exporter:
    image: prom/node-exporter-linux-arm64:v1.3.1
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
  cadvisor:
    # no arm image yet image: gcr.io/cadvisor/cadvisor:v0.39.3
    build:
      context: ./
      dockerfile: Dockerfile.cadvisor
    container_name: cadvisor
    privileged: true
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    ports:
      - 8080:8080
