- hostname:
    name: "{{ inventory_hostname }}"

- name: Only run "update_cache=yes" if the last run older than 3600 seconds ago
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install basic packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
  become: true

- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: create data dir
  file: 
    path: "{{ data_dir }}"
    state: directory 

# ceph uses block? maybe no format?
# - name: format drive
#   filesystem: 
#     fstype: ext4
#     dev: "{{ data_dir }}"

# - name: mount ssd
#   mount:
#     src: UUID={{ ssd_uuid }}
#     path: "{{ data_dir }}"
#     fstype: auto
#     opts: defaults,nobootwait dump=0 passno=2 
#     state: mounted
