{
 "title": "Homeserver",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Container Uptime",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - (sum without(instance,job)(node_boot_time_seconds) > on(node) group_right sum by(node,name) (container_start_time_seconds{name!=\"\",name!=\"cadvisor\",name!=\"node_exporter\"}) or sum by(node,name) (container_start_time_seconds{name!=\"\",name!=\"cadvisor\",name!=\"node_exporter\"}))"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name!=\"\",name!=\"cadvisor\",name!=\"node_exporter\"}) by (node,name) \n/ ignoring(name) group_left sum without(instance,job)(node_memory_MemTotal_bytes)\n\n",
     "legendFormat": "{{node}}:{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(node,name) (rate(container_cpu_usage_seconds_total{name!=\"\",name!=\"cadvisor\",name!=\"node_exporter\"}[5m]))/ignoring(name) group_left sum without(job,boot_id,machine_id,system_uuid,instance)(machine_cpu_cores)\n",
     "legendFormat": "{{node}}:{{name}}"
    },
    {}
   ]
  },
  {
   "title": "Node Uptime",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "time()-node_boot_time_seconds" }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 9 },
   "targets": [
    { "expr": "node_thermal_zone_temp", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (node) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Mem Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemFree_bytes)/node_memory_MemTotal_bytes",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Cadvisor",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 17, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"cadvisor\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node Exporter",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 17, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node_exporter\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=~\"eth0|wlx.*\"}[5m])",
     "legendFormat": "{{node}}:recieve"
    },
    {
     "expr": "-rate(node_network_transmit_bytes_total{device=~\"eth0|wlx.*\"}[5m])",
     "legendFormat": "{{node}}:transmit"
    }
   ]
  },
  {
   "title": "Free FS Space",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{fstype!=\"rootfs\",mountpoint=\"/\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Free Data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 13, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{fstype!=\"rootfs\",mountpoint=\"/data\"}",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}