FROM arm64v8/golang:1.17.6-stretch as builder
ENV CADVISOR_VERSION "v0.39.3"
RUN apt-get update && apt-get install -y git dmsetup && apt-get clean
RUN git clone --branch ${CADVISOR_VERSION} https://github.com/google/cadvisor.git /go/src/github.com/google/cadvisor
WORKDIR /go/src/github.com/google/cadvisor
RUN make build

FROM arm64v8/debian:stretch-slim
COPY --from=builder /go/src/github.com/google/cadvisor/cadvisor /usr/bin/cadvisor
EXPOSE 8080
ENTRYPOINT ["/usr/bin/cadvisor", "-logtostderr"]
