apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  id: 1
  orgId: 1
  uid: C3hREdJnk
  typeName: Prometheus
  typeLogoUrl: public/app/plugins/datasource/prometheus/img/prometheus_logo.svg
  access: proxy
  url: http://prometheus:9090
  basicAuth: false
  isDefault: true
  readOnly: true
