
# create directories for config files
- name: Creates casc directory
  file:
    group: root
    mode: 0755
    owner: root
    path: "{{ install_directory }}"
    state: directory

- name: Creates directory for config files
  file:
    group: root
    mode: 0755
    owner: root
    path: "{{ install_directory }}/configs"
    state: directory

- name: Creates directory for ssl
  file:
    group: root
    mode: 0755
    owner: root
    path: "{{ install_directory }}/ssl_conf"
    state: directory

- name: copy .jks file
  copy:
    src: "var/lib/casc/ssl_conf/{{ instance_name }}.jks"
    dest: "{{ install_directory }}/ssl_conf/jenkins_keystore.jks"
    group: root
    mode: 0755
    owner: root

- name: copy vault.cert file
  copy:
    src: "var/lib/casc/ssl_conf/vault.cert"
    dest: "{{ install_directory }}/ssl_conf/vault.cert"
    group: root
    mode: 0755
    owner: root

- name: copy env file, chmod 600
  template:
    src: "var/lib/casc/envs"
    dest: "{{ install_directory }}/envs"
    group: root
    mode: 0600
    owner: root

- name: Copies configuration files
  copy:
    src: "{{ item }}"
    dest: "{{ install_directory }}/configs"
    group: root
    mode: 0755
    owner: root
  with_fileglob:
    - var/lib/casc/configs/*
  register: casc_configs

- name: Copies template files
  template:
    src: "{{ item }}"
    dest: "{{ install_directory }}/configs"
    group: root
    mode: 0755
    owner: root
  with_fileglob:
    - ../templates/var/lib/casc/configs/*

# the following two commands are nessisary until logstash can be configured by CASC
# see https://issues.jenkins-ci.org/browse/JENKINS-52697
- name: Creates groovy directory
  file:
    group: root
    mode: 0755
    owner: root
    path: "{{ install_directory }}/groovy"
    state: directory

- name: Copies configuration files
  copy:
    src: "{{ item }}"
    dest: "{{ install_directory }}/groovy"
    group: root
    mode: 0755
    owner: root
  with_fileglob:
    - var/lib/casc/init.groovy.d/*
  register: groovy_scripts
  when: create_jobify_user
