- name: Initialize the Kubernetes cluster using kubeadm
    command: "kubeadm init --apiserver-advertise-address {{ static_ip }} --apiserver-cert-extra-sans {{ static_ip }}  --node-name {{ inventory_host }} --pod-network-cidr=192.168.0.0/16"
# NOT WORKING

- name: Install calico pod network
  command: kubectl create -f https://docs.projectcalico.org/v3.4/getting-started/kubernetes/installation/hosted/calico.yaml
  # need to check if calico not created!

# check for existance of token file
- name: check if token file exists
  stat: 
    path: /home/rock64/join_command
  register: join_command_exists

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command
  when: join_command_exists == False

- debug:
    msg: Please encrypt the token file, and store it as a default join_command variable in the nodes role