# read node name from /etc/nodeinfo/name as variable


#over ride /etc/hosts

- name: install required packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages: 
    - iptables
    - dnsmasq
  become: true

- name: template netplan
  template:
    src: etc/netplan/eth0.yaml.j2
    dest: /etc/netplan/eth0.yaml
  
- name: execute netplan
  command: netplan apply
  register: hi
  become: true

- name: template dnsmasq configuration
  template:
    src: etc/dnsmasq.d/custom-dnsmasq.conf.j2
    dest: /etc/dnsmasq.d/custom-dnsmasq.conf

- name: start dnsmasq
  systemd:
    name: dnsmasq
    state: reloaded
    daemon_reload: yes


# sudo iptables -F
# sudo iptables -t nat -F
# sudo iptables -t nat -A POSTROUTING -o $wlan -j MASQUERADE
# sudo iptables -A FORWARD -i $wlan -o $eth -m state --state RELATED,ESTABLISHED -j ACCEPT
# sudo iptables -A FORWARD -i $eth -o $wlan -j ACCEPT
